version: '2'
services:
    jhipsterbank-elasticsearch:
        container_name: jhipsterbank-elasticsearch
        image: elasticsearch:2.3.5
        # volumes:
        #     - ~/volumes/jhipster/jhipsterbank/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
